const $=id=>document.getElementById(id);
let charts={class:null,drift:null,status:null,vdd:null,shap:null};
function notice(id,text,error=false){$(id).textContent=text||"";$(id).className=error?"notice error":"notice"}
async function api(url,opt={}){const r=await fetch(url,opt);const text=await r.text();let d;try{d=text?JSON.parse(text):{}}catch{throw Error(`Server returned HTTP ${r.status}. Check the backend terminal.`)}if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}
function metric(n,v){return `<div class="metric"><span>${n}</span><strong>${v}</strong></div>`}function pct(v){return `${(100*Number(v)).toFixed(1)}%`}function fmt(v,d=4){return v==null||!Number.isFinite(Number(v))?'—':Number(v).toFixed(d)}
const PALETTE={accent:'#1F3F5C',heat:'#C1521B',good:'#1F6E4E',warn:'#8A5A07',bad:'#A3372B',muted:'#57615A',grid:'#E1E4DB'};
function statusColor(k){const s=String(k).toUpperCase();return s==='PASS'?PALETTE.good:s==='WARNING'?PALETTE.warn:s==='REJECT'?PALETTE.bad:PALETTE.accent}
function chartDefaults(){return {responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:PALETTE.muted,font:{size:10,family:'IBM Plex Mono'}}}},scales:{x:{ticks:{color:PALETTE.muted,font:{family:'IBM Plex Mono',size:10}},grid:{color:PALETTE.grid}},y:{ticks:{color:PALETTE.muted,font:{family:'IBM Plex Mono',size:10}},grid:{color:PALETTE.grid}}}}}
async function loadStatus(){try{const d=await api('/api/status');$('heroRows').textContent=d.rows?d.rows.toLocaleString():'—';$('heroStatus').textContent=d.trained?'Ready':'Awaiting training';if(d.trained){$('modelBadge').textContent='MODEL READY';$('modelBadge').className='badge ready';$('testUploadBtn').disabled=false;$('predictBtn').disabled=false;$('batchBtn').disabled=false}}catch(e){$('modelBadge').textContent='BACKEND OFFLINE';$('modelBadge').className='badge'}}
async function upload(e){e.preventDefault();const f=$("datasetFile").files[0];if(!f)return;const fd=new FormData();fd.append("file",f);notice("uploadResult","Loading training dataset…");try{const d=await api("/api/upload",{method:"POST",body:fd});notice("uploadResult",`Loaded ${d.filename} · ${d.rows.toLocaleString()} rows · ${d.columns.length} columns.`);$('heroRows').textContent=d.rows.toLocaleString();$('trainBtn').disabled=false;$('componentSelect').disabled=false;$('batchBtn').disabled=true;preview(d.preview,d.columns,"tableWrap");const c=await api("/api/components");$("componentSelect").innerHTML='<option value="">Select component</option>'+c.components.map(x=>`<option>${x}</option>`).join("")}catch(e){notice("uploadResult",e.message,true)}}
async function train(){$("trainBtn").disabled=true;notice("trainResult","Training real XGBoost + Isolation Forest models… please wait.");try{const d=await api("/api/train",{method:"POST"});$('modelBadge').textContent='MODEL READY';$('modelBadge').className='badge ready';$('heroStatus').textContent='Ready';$('testUploadBtn').disabled=false;$('predictBtn').disabled=false;$('batchBtn').disabled=false;notice("trainResult",`Trained on ${d.split.train_rows.toLocaleString()} rows and evaluated on ${d.split.holdout_rows.toLocaleString()} untouched holdout rows.`);renderClassMetrics("trainClassMetrics",d.failure_train_metrics);renderClassMetrics("holdoutClassMetrics",d.failure_holdout_metrics);renderDriftMetrics("trainDriftMetrics",d.drift_train_metrics);renderDriftMetrics("holdoutDriftMetrics",d.drift_holdout_metrics);$('splitLabel').textContent=`${Math.round(d.split.train_fraction*100)} / ${Math.round(d.split.holdout_fraction*100)} HOLDOUT`;renderClassChart(d.failure_holdout_metrics);renderDriftChart(d.drift_holdout_metrics);const h=d.failure_holdout_metrics;$('classificationMetrics').innerHTML=[metric('Accuracy',pct(h.accuracy)),metric('Balanced accuracy',pct(h.balanced_accuracy)),metric('Precision',h.precision.toFixed(3)),metric('Recall',h.recall.toFixed(3)),metric('F1',h.f1.toFixed(3)),metric('PR-AUC',h.pr_auc.toFixed(3))].join('');$('trainConfusion').innerHTML=`<div class="confusionTitle">Holdout confusion matrix · Accuracy ${pct(h.accuracy)}</div><table><thead><tr><th></th><th>Predicted PASS</th><th>Predicted FAIL</th></tr></thead><tbody><tr><th>Actual PASS</th><td>${h.true_negative}</td><td>${h.false_positive}</td></tr><tr><th>Actual FAIL</th><td>${h.false_negative}</td><td>${h.true_positive}</td></tr></tbody></table>`}catch(e){notice("trainResult",e.message,true);$('trainBtn').disabled=false}}
function renderClassMetrics(id,m){$(id).innerHTML=[metric("Accuracy",pct(m.accuracy)),metric("Balanced",pct(m.balanced_accuracy)),metric("Precision",m.precision.toFixed(3)),metric("Recall",m.recall.toFixed(3)),metric("F1",m.f1.toFixed(3)),metric("ROC-AUC",m.roc_auc.toFixed(3))].join('')}
function renderDriftMetrics(id,m){$(id).innerHTML=[metric('MAE',fmt(m.mae,5)),metric('RMSE',fmt(m.rmse,5)),metric('R²',fmt(m.r2,4))].join('')}
function renderClassChart(m){if(charts.class)charts.class.destroy();charts.class=new Chart($('classChart'),{type:'bar',data:{labels:['Accuracy','Precision','Recall','F1','ROC-AUC','PR-AUC'],datasets:[{label:'Holdout score',data:[m.accuracy,m.precision,m.recall,m.f1,m.roc_auc,m.pr_auc],backgroundColor:PALETTE.accent,borderRadius:3}]},options:{...chartDefaults(),scales:{...chartDefaults().scales,y:{...chartDefaults().scales.y,min:0,max:1}}}})}
function renderDriftChart(m){if(charts.drift)charts.drift.destroy();charts.drift=new Chart($('driftChart'),{type:'bar',data:{labels:['MAE','RMSE','R²'],datasets:[{label:'Holdout',data:[m.mae,m.rmse,m.r2],backgroundColor:PALETTE.heat,borderRadius:3}]},options:chartDefaults()})}
async function uploadTest(e){e.preventDefault();const f=$("testFile").files[0];if(!f)return;const fd=new FormData();fd.append("file",f);notice("testUploadResult","Loading custom test dataset…");try{const d=await api("/api/test-upload",{method:"POST",body:fd});$('testBadge').textContent=`CUSTOM TEST · ${d.rows.toLocaleString()} ROWS`;$('testBadge').className='badge ready';$('evaluateBtn').disabled=false;$('testComponentSelect').disabled=false;$('testPredictBtn').disabled=false;notice("testUploadResult",`Loaded ${d.filename}. No retraining will occur.`);preview(d.preview,d.columns,"customTableWrap");const c=await api('/api/test-components');$('testComponentSelect').innerHTML='<option value="">Select test component</option>'+c.components.map(x=>`<option>${x}</option>`).join('')}catch(e){notice('testUploadResult',e.message,true)}}
async function evaluateTest(){$('evaluateBtn').disabled=true;notice('testUploadResult','Evaluating the complete custom test set…');try{const d=await api('/api/test-evaluate',{method:'POST'}),c=d.classification_metrics,dr=d.drift_metrics;$('testMetrics').innerHTML=`<div class="metric-grid">${metric('Accuracy',pct(c.accuracy))}${metric('Balanced',pct(c.balanced_accuracy))}${metric('Precision',c.precision.toFixed(3))}${metric('Recall',c.recall.toFixed(3))}${metric('F1',c.f1.toFixed(3))}${metric('PR-AUC',c.pr_auc.toFixed(3))}</div><div class="confusion"><div class="confusionTitle">Custom test confusion matrix</div><table><thead><tr><th></th><th>Predicted PASS</th><th>Predicted FAIL</th></tr></thead><tbody><tr><th>Actual PASS</th><td>${c.true_negative}</td><td>${c.false_positive}</td></tr><tr><th>Actual FAIL</th><td>${c.false_negative}</td><td>${c.true_positive}</td></tr></tbody></table></div><div class="counts">${Object.entries(d.classification_results).map(([k,v])=>`<div class="count"><b>${k}</b>: ${v}</div>`).join('')}</div>${dr?`<div class="metric-grid">${metric('Drift MAE',fmt(dr.mae,5))}${metric('Drift RMSE',fmt(dr.rmse,5))}${metric('Drift R²',fmt(dr.r2,4))}</div>`:''}`;$('downloadTestBtn').classList.remove('hidden');notice('testUploadResult','Custom test evaluation complete.')}catch(e){notice('testUploadResult',e.message,true)}finally{$('evaluateBtn').disabled=false}}
async function analyzeTest(){const id=$('testComponentSelect').value;if(!id)return;$('testPrediction').innerHTML='<div class="result-card">Analyzing…</div>';try{renderComponent(await api('/api/test-predict/'+encodeURIComponent(id)),true)}catch(e){$('testPrediction').innerHTML=`<div class="result-card notice error">${e.message}</div>`}}
async function predict(){const id=$('componentSelect').value;if(!id)return;$('prediction').innerHTML='<div class="result-card">Analyzing…</div>';try{renderComponent(await api('/api/predict/'+encodeURIComponent(id)),false)}catch(e){$('prediction').innerHTML=`<div class="result-card notice error">${e.message}</div>`}}
function renderComponent(d,isTest){const target=isTest?'testPrediction':'prediction';const actual=d.actual_failure!==undefined?`<p><b>Actual outcome:</b> ${d.actual_failure?'FAIL':'PASS'} · <b>${d.classification_result}</b></p>`:'';$(target).innerHTML=`<div class="result-card"><div class="muted">${isTest?'Independent test':'Training'} component · ${d.component_id}</div><div class="status ${d.status}">${d.status}</div><div class="bars"><div class="barline"><span>Failure probability</span><div class="track"><div class="fill" style="width:${100*d.failure_probability}%"></div></div><b>${pct(d.failure_probability)}</b></div><div class="barline"><span>Anomaly severity</span><div class="track"><div class="fill" style="width:${100*d.anomaly_score}%"></div></div><b>${pct(d.anomaly_score)}</b></div></div><p><b>Anomaly:</b> ${d.anomaly_level}</p><p><b>Predicted VDD drift:</b> ${fmt(d.predicted_vdd_drift,6)} V</p><p><b>Predicted VDD at 168h:</b> ${fmt(d.predicted_vdd_168h,6)} V</p>${actual}</div>`;renderVddChart(d);renderShap(d);$('details').innerHTML=`<div class="result-card"><h3>${isTest?'Independent test':'Training'} decision details</h3><p>Failure prediction: <b>${d.failure_prediction?'FAIL':'PASS'}</b></p>${actual}<p>Isolation Forest: <b>${d.anomaly_level}</b> (${pct(d.anomaly_score)})</p><p>168h VDD forecast: <b>${fmt(d.predicted_vdd_168h,6)} V</b></p></div>`}
function renderVddChart(d){if(!d.vdd_series)return;if(charts.vdd)charts.vdd.destroy();const vals=d.vdd_series.map(x=>x.value);charts.vdd=new Chart(document.createElement('canvas'),{type:'line',data:{labels:d.vdd_series.map(x=>x.label),datasets:[{label:'VDD',data:vals,tension:.3,pointRadius:3,borderColor:PALETTE.accent,backgroundColor:PALETTE.accent,pointBackgroundColor:PALETTE.accent}]},options:chartDefaults()});const old=$('details').querySelector('.vdd-holder');if(old)old.remove();const holder=document.createElement('div');holder.className='chart-card vdd-holder';holder.innerHTML='<div class="chart-head"><h3>VDD trajectory</h3><span>observed + 168h forecast</span></div>';holder.appendChild(charts.vdd.canvas);$('details').appendChild(holder)}
function renderShap(d){if(!d.shap||!d.shap.length)return;const old=$('details').querySelector('.shap-holder');if(old)old.remove();if(charts.shap)charts.shap.destroy();const holder=document.createElement('div');holder.className='chart-card shap-holder';holder.innerHTML='<div class="chart-head"><h3>SHAP feature impact</h3><span>top drivers</span></div><canvas id="shapCanvas"></canvas>';$('details').appendChild(holder);charts.shap=new Chart($('shapCanvas'),{type:'bar',data:{labels:d.shap.map(x=>x.feature),datasets:[{label:'SHAP value',data:d.shap.map(x=>x.shap_value),backgroundColor:d.shap.map(x=>x.shap_value>=0?PALETTE.bad:PALETTE.good),borderRadius:3}]},options:{...chartDefaults(),indexAxis:'y'}})}
async function batch(){$('batchBtn').disabled=true;$('batchResult').innerHTML='<p class="muted">Running batch inference…</p>';try{const d=await api('/api/predict-all',{method:'POST'});$('batchResult').innerHTML=`<p>Processed <b>${d.count.toLocaleString()}</b> components.</p><div class="counts">${Object.entries(d.status_distribution).map(([k,v])=>`<div class="count"><b>${k}</b>: ${v}</div>`).join('')}</div>`;$('downloadBtn').classList.remove('hidden');renderStatusChart(d.status_distribution)}catch(e){$('batchResult').innerHTML=`<p class="notice error">${e.message}</p>`}finally{$('batchBtn').disabled=false}}
function renderStatusChart(dist){if(charts.status)charts.status.destroy();charts.status=new Chart($('statusChart'),{type:'doughnut',data:{labels:Object.keys(dist),datasets:[{data:Object.values(dist),backgroundColor:Object.keys(dist).map(statusColor),borderColor:'#fff',borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom',labels:{color:PALETTE.muted,font:{size:10,family:'IBM Plex Mono'}}}}}})}
function preview(rows,cols,target){if(!rows.length){$(target).textContent='No preview rows.';return}$(target).innerHTML='<table><thead><tr>'+cols.map(c=>`<th>${c}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>`<td>${r[c]??''}</td>`).join('')+'</tr>').join('')+'</tbody></table>'}
$('uploadForm').addEventListener('submit',upload);$('trainBtn').addEventListener('click',train);$('testUploadForm').addEventListener('submit',uploadTest);$('evaluateBtn').addEventListener('click',evaluateTest);$('testPredictBtn').addEventListener('click',analyzeTest);$('predictBtn').addEventListener('click',predict);$('batchBtn').addEventListener('click',batch);window.addEventListener('DOMContentLoaded',loadStatus);
